// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAejsYgzq-_Geac6NLVHeRPXE2RIOO4-gc',
    appId: '1:961006214553:web:711000550bc8fa88a64708',
    messagingSenderId: '961006214553',
    projectId: 'getxecommerce-9f8f4',
    authDomain: 'getxecommerce-9f8f4.firebaseapp.com',
    storageBucket: 'getxecommerce-9f8f4.appspot.com',
    measurementId: 'G-28HJ510GKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_89SYyB0mJNB8ZLf_6UZMxxpApTzRJm4',
    appId: '1:961006214553:android:e41993bffaaf4b50a64708',
    messagingSenderId: '961006214553',
    projectId: 'getxecommerce-9f8f4',
    storageBucket: 'getxecommerce-9f8f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3mlbBF9A45MizChFeiZZxEY7LoM2Srs4',
    appId: '1:961006214553:ios:0194e8a775c9519aa64708',
    messagingSenderId: '961006214553',
    projectId: 'getxecommerce-9f8f4',
    storageBucket: 'getxecommerce-9f8f4.appspot.com',
    androidClientId: '961006214553-l1s7ij249raes11fdce3qecuv72d9q32.apps.googleusercontent.com',
    iosClientId: '961006214553-tdsjg7ubuep0d0dfm9crbra9biapvcld.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3mlbBF9A45MizChFeiZZxEY7LoM2Srs4',
    appId: '1:961006214553:ios:0194e8a775c9519aa64708',
    messagingSenderId: '961006214553',
    projectId: 'getxecommerce-9f8f4',
    storageBucket: 'getxecommerce-9f8f4.appspot.com',
    androidClientId: '961006214553-l1s7ij249raes11fdce3qecuv72d9q32.apps.googleusercontent.com',
    iosClientId: '961006214553-tdsjg7ubuep0d0dfm9crbra9biapvcld.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAejsYgzq-_Geac6NLVHeRPXE2RIOO4-gc',
    appId: '1:961006214553:web:e63236f008994259a64708',
    messagingSenderId: '961006214553',
    projectId: 'getxecommerce-9f8f4',
    authDomain: 'getxecommerce-9f8f4.firebaseapp.com',
    storageBucket: 'getxecommerce-9f8f4.appspot.com',
    measurementId: 'G-5PP03JYM20',
  );

}